---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - sudo apt-get install -y apache2
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
