---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - sudo apt-get update && sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ondrej/php5-5.6
  - sudo apt-get update && sudo apt-get upgrade
  - sudo apt-get install php5
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
