---

language: python

python:
  - 2.7

install:
  - pip install ansible

script:
  - git clone https://github.com/geerlingguy/ansible-role-git roles/geerlingguy.git
  - git clone https://github.com/geerlingguy/ansible-role-php roles/geerlingguy.php
  - git clone https://github.com/geerlingguy/ansible-role-composer roles/geerlingguy.composer
  - git clone https://github.com/geerlingguy/ansible-role-drush roles/geerlingguy.drush
  - cd tests
  - ansible-playbook -i inventory playbook.yml --syntax-check
  - ansible-playbook -i inventory playbook.yml --sudo -vvvv
