---
# file: roles/fubarhouse.dvm/tasks/dvm.yml

- name: DVM | Check
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat:
    path: "/usr/local/bin/dvm"
  register: dvm_result
  tags:
    - drush
    - dvm

- name: "DVM | Verifying file system"
  become: yes
  become_user: root
  file:
    path: "{{ dvm_dir }}"
    mode: 0777
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  tags:
    - drush
    - dvm

- name: DVM | Git
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: https://github.com/fubarhouse/dvm
    dest: "{{ dvm_dir }}"
    clone: yes
    update: yes
    version: master
  tags:
    - drush
    - dvm

- name: DVM | Symlinking DVM
  sudo: yes
  sudo_user: root
  file:
    src: "{{ dvm_location }}"
    dest: "/usr/local/bin/dvm"
    owner: root
    group: root
    mode: 0777
    state: link
    force: yes
  tags:
    - drush
    - dvm

- name: DVM | Symlinking Drush
  sudo: yes
  sudo_user: root
  file:
    src: "{{ dvm_dir }}/drush"
    dest: "/usr/local/bin/drush"
    owner: root
    group: root
    mode: 0777
    state: link
    force: yes
  tags:
    - drush
    - dvm

- name: "DVM | Run initializer"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: "{{ dvm_location }} initialize"
  tags:
    - drush
    - dvm

- name: "DVM | Update/Install Drush"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: "{{ dvm_location }} update"
  tags:
    - drush
    - dvm
  when: dvm_drush_update == true

- name: "DVM | Ensure DVM has installed Drush"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: "{{ dvm_location }} install {{ dvm_drush_version }}"
  tags:
    - drush
    - dvm
  when: dvm_drush_update != true

- name: "DVM | Ensure DVM is using Drush"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  raw: "{{ dvm_location }} use {{ dvm_drush_version }}"
  tags:
    - drush
    - dvm
  when: dvm_drush_update != true

- name: DVM | Install packages
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: dvm pkg install {{ item }}
  with_items:
    - "{{ dvm_packages }}"
  tags:
    - drush
    - dvm
  when: dvm_install_packages == true
