---
# file: roles/fubarhouse.dvm/tasks/dvm.yml

- name: "DVM | Clean-up (1/2)"
  become: yes
  become_user: root
  file:
    path: "{{ fubarhouse_dvm.dvm_dir }}"
    state: absent
    force: yes
  when: "{{ fubarhouse_dvm.clean_install }} == true"

- name: "DVM | Clean-up (2/2)"
  become: yes
  become_user: root
  file:
    path: "{{ item.dest }}"
    state: absent
    force: yes
  when: "{{ fubarhouse_dvm.clean_install }} == true"
  with_items: "{{ fubarhouse_dvm.symlinks }}"

- name: DVM | Check
  become: yes
  become_user: "{{ fubarhouse_user }}"
  stat:
    path: "{{ fubarhouse_dvm.dvm_dir }}"
  register: fubarhouse_dvm_dvm_result
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.install_dvm }} == true"

- name: DVM | Git
  git:
    repo: "{{ fubarhouse_dvm.dvm_repo }}"
    dest: "{{ fubarhouse_dvm.dvm_dir }}"
    force: yes
    clone: yes
    update: yes
    version: master
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.install_dvm }} == true"

- name: "DVM | Initializing"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} initialize"
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.install_dvm }} == true"

- name: "DVM | Update"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} update"
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.dvm_drush_update }} == true"

- name: "DVM | Install Drush"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} install {{ item }}"
  with_items: "{{ drush_versions }}"
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.dvm_drush_update }} != true"

- name: "DVM | Ensure DVM is using Drush"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} use {{ drush_version }}"
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.dvm_drush_update }} != true"

- name: DVM | Install packages
  become: yes
  become_user: "{{ fubarhouse_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} pkg install {{ item }}"
  with_items:
    - "{{ drush_packages }}"
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.dvm_install_packages }} == true"

- name: DVM | Ensure symlinks are correct
  become: yes
  become_user: "root"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ fubarhouse_user }}"
    mode: 0777
    state: link
    force: yes
  tags:
    - drush
    - dvm
  when: "{{ fubarhouse_dvm.install_dvm }} == true"
  with_items: "{{ fubarhouse_dvm.symlinks }}"