---
# file: roles/fubarhouse.dvm/tasks/dvm.yml

- name: "DVM | Clean-up (1/3)"
  become: yes
  become_user: root
  file:
    path: "{{ fubarhouse_dvm.dvm_dir }}"
    state: absent
  when: fubarhouse_dvm.clean_install

- name: "DVM | Clean-up (2/3)"
  become: yes
  become_user: root
  file:
    path: "{{ fubarhouse_dvm.dvm_symlink }}"
    state: absent
  when: fubarhouse_dvm.clean_install

- name: "DVM | Clean-up (3/3)"
  become: yes
  become_user: root
  file:
    path: "{{ fubarhouse_dvm.drush_symlink }}"
    state: absent
  when: fubarhouse_dvm.clean_install

- name: DVM | Check
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  stat:
    path: "{{ fubarhouse_dvm.dvm_dir }}"
  register: fubarhouse_dvm_dvm_result
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.install_dvm

- name: DVM | Git
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  git:
    repo: "{{ fubarhouse_dvm.dvm_repo }}"
    dest: "{{ fubarhouse_dvm.dvm_dir }}"
    clone: yes
    update: yes
    version: master
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.install_dvm

- name: DVM | Symlinking DVM
  become: yes
  become_user: "root"
  file:
    src: "{{ fubarhouse_dvm.dvm_dir }}/dvm"
    dest: "{{ fubarhouse_dvm.dvm_symlink }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0777
    state: link
    force: yes
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.install_dvm

- name: DVM | Symlinking Drush
  become: yes
  become_user: "root"
  file:
    src: "{{ fubarhouse_dvm.dvm_dir }}/drush"
    dest: "{{ fubarhouse_dvm.drush_symlink }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0777
    state: link
    force: yes
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.install_dvm

- name: "DVM | Initializing"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} initialize"
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.install_dvm

- name: "DVM | Update"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} update"
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.dvm_drush_update

- name: "DVM | Install Drush"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} install {{ item }}"
  with_items: "{{ fubarhouse_dvm.installed_versions }}"
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.dvm_drush_update != true

- name: "DVM | Ensure DVM is using Drush"
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} use {{ fubarhouse_dvm.dvm_drush_version }}"
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.dvm_drush_update != true

- name: DVM | Install packages
  become: yes
  become_user: "{{ ansible_ssh_user }}"
  shell: "{{ fubarhouse_dvm.dvm_dir }}/{{ fubarhouse_dvm.dvm_exec }} pkg install {{ item }}"
  with_items:
    - "{{ fubarhouse_dvm.packages }}"
  tags:
    - drush
    - dvm
  when: fubarhouse_dvm.dvm_install_packages
