---
# file: roles/fubarhouse.dvm/tasks/main.yml

- name: "Define user variable for ssh user"
  set_fact:
    fubarhouse_user: "{{ ansible_ssh_user }}"
  when: ansible_ssh_user is defined

- name: "Define user variable for non-ssh user"
  set_fact:
    fubarhouse_user: "{{ ansible_user_id }}"
  when: ansible_ssh_user is not defined

- name: "Define OS-specific variables"
  include_vars: "config-{{ ansible_os_family }}.yml"
  when: fubarhouse_dvm is not defined

- include: "dependencies-{{ ansible_os_family}}.yml"

- include: dvm.yml
