---

fubarhouse_dvm:
  # User
  user: "{{ fubarhouse_user }}"
  user_dir: "/Users/{{ fubarhouse_user }}"
  # Clean install
  clean_install: false
  # Process controls
  install_dvm: true
  dvm_drush_update: false
  dvm_install_packages: true
  # Repositories
  dvm_repo: "https://github.com/fubarhouse/dvm"
  # Install directories
  dvm_dir: "/Users/{{ fubarhouse_user }}/.dvm"
  # Symlinks
  symlinks:
    - name: dvm
      src: "/Users/{{ fubarhouse_user }}/.dvm/dvm"
      dest: "/usr/local/bin/dvm"
    - name: drush
      src: "/Users/{{ fubarhouse_user }}/.dvm/drush"
      dest: "/usr/local/bin/drush"
  # Install paths
  # Executables
  dvm_exec: "dvm"